{
 "title": "Measures",
 "description": "Print humidity and temperature values",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Last report",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "alias": "Measure",
     "groupBy": [
      { "params": [ "addr" ], "type": "tag" }
     ],
     "measurement": "measures",
     "query": "SELECT last(\"addr\") FROM \"measures\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "addr" ], "type": "field" }
      ],
      [
       { "params": [ "measure" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Graphics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Temperaure",
   "type": "timeseries",
   "description": "Print temperature values from any device",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "alias": "Temperature",
     "measurement": "measures",
     "query": "SELECT \"measure\" FROM \"measures\" WHERE (\"sensor_prop_id\" = '0056') AND $timeFilter",
     "select": [
      [
       { "params": [ "measure" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sensor_prop_id", "operator": "=", "value": "0056" }
     ]
    }
   ]
  },
  {
   "title": "Temperature 00AA",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "alias": "Temperature 00AA",
     "measurement": "measures",
     "select": [
      [
       { "params": [ "measure" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sensor_prop_id", "operator": "=", "value": "0056" },
      { "condition": "AND", "key": "addr", "operator": "=", "value": "00AA" }
     ]
    }
   ]
  },
  {
   "title": "Temperature 00AB",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "alias": "Temperature 00AB",
     "measurement": "measures",
     "select": [
      [
       { "params": [ "measure" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sensor_prop_id", "operator": "=", "value": "0056" },
      { "condition": "AND", "key": "addr", "operator": "=", "value": "00AB" }
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "description": "Print humidity fron any device",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "alias": "Humidity",
     "measurement": "measures",
     "query": "SELECT \"measure\" FROM \"measures\" WHERE (\"sensor_prop_id\" = '0080') AND $timeFilter",
     "select": [
      [
       { "params": [ "measure" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sensor_prop_id", "operator": "=", "value": "0080" }
     ]
    }
   ]
  },
  {
   "title": "Humidity 00AA",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "alias": "Humidity 00AA",
     "measurement": "measures",
     "select": [
      [
       { "params": [ "measure" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sensor_prop_id", "operator": "=", "value": "0080" },
      { "condition": "AND", "key": "addr", "operator": "=", "value": "00AA" }
     ]
    }
   ]
  },
  {
   "title": "Humidity 00AB",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "alias": "Humidity 00AB",
     "measurement": "measures",
     "select": [
      [
       { "params": [ "measure" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sensor_prop_id", "operator": "=", "value": "0080" },
      { "condition": "AND", "key": "addr", "operator": "=", "value": "00AB" }
     ]
    }
   ]
  }
 ]
}